config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('index', views.index_view),
    path('home', views.index_view, name='home'),
    path('about', views.about_view, name='sobre'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
#  hello/urls.py

from django.shortcuts import render
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "portfolio"

urlpatterns = [
    path('index', views.index_view),
    path('home', views.home_page_view, name='home'),
    path('about', views.about_view, name='sobre'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render
import datetime


def home_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)


def layout(request):
    return render(request, 'portfolio/templates/portfolio/layout.html')


#def quizz(request):
#   if request.method == 'POST'
#      n = request.POST['nome']
#      p = pontuacao_quizz(request)
#      r = PontuacaoQuizz(nome=n, pontuacao=p)
#      r.save()

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


</head>

<body>

    <header>
        <div>
        <Title>Tomé Roque</Title>
        <nav >
            <a href="{% url 'portfolio:home' %}">Home</a>
            <a></a>
        </nav>

    </div>
    </header>

    <main>
        {% block main %}
        {% endblock main %}
    </main>

    <footer>

        <div style="margin-center:auto;">
            ULHT, 2022
        </div>

    </footer>

</body>
</html>